import 'app_state.dart';

/// دولة — كود ISO (حرفين، بيطابق `country_code` في Open-Meteo) + اسم عربي/إنجليزي.
class Country {
  final String code;
  final String ar;
  final String en;
  const Country(this.code, this.ar, this.en);

  String get name => AppState.isEnglish ? en : ar;
}

/// كل دول العالم (ISO 3166-1). مصر من ضمنها. الاسم بالعربي والإنجليزي.
const List<Country> kCountries = [
  Country('EG', 'مصر', 'Egypt'),
  Country('SA', 'السعودية', 'Saudi Arabia'),
  Country('AE', 'الإمارات', 'United Arab Emirates'),
  Country('KW', 'الكويت', 'Kuwait'),
  Country('QA', 'قطر', 'Qatar'),
  Country('BH', 'البحرين', 'Bahrain'),
  Country('OM', 'عُمان', 'Oman'),
  Country('YE', 'اليمن', 'Yemen'),
  Country('IQ', 'العراق', 'Iraq'),
  Country('SY', 'سوريا', 'Syria'),
  Country('JO', 'الأردن', 'Jordan'),
  Country('LB', 'لبنان', 'Lebanon'),
  Country('PS', 'فلسطين', 'Palestine'),
  Country('SD', 'السودان', 'Sudan'),
  Country('LY', 'ليبيا', 'Libya'),
  Country('TN', 'تونس', 'Tunisia'),
  Country('DZ', 'الجزائر', 'Algeria'),
  Country('MA', 'المغرب', 'Morocco'),
  Country('MR', 'موريتانيا', 'Mauritania'),
  Country('SO', 'الصومال', 'Somalia'),
  Country('DJ', 'جيبوتي', 'Djibouti'),
  Country('KM', 'جزر القمر', 'Comoros'),
  Country('TR', 'تركيا', 'Turkey'),
  Country('IR', 'إيران', 'Iran'),
  Country('AF', 'أفغانستان', 'Afghanistan'),
  Country('PK', 'باكستان', 'Pakistan'),
  Country('IN', 'الهند', 'India'),
  Country('BD', 'بنجلاديش', 'Bangladesh'),
  Country('LK', 'سريلانكا', 'Sri Lanka'),
  Country('NP', 'نيبال', 'Nepal'),
  Country('ID', 'إندونيسيا', 'Indonesia'),
  Country('MY', 'ماليزيا', 'Malaysia'),
  Country('SG', 'سنغافورة', 'Singapore'),
  Country('BN', 'بروناي', 'Brunei'),
  Country('TH', 'تايلاند', 'Thailand'),
  Country('VN', 'فيتنام', 'Vietnam'),
  Country('PH', 'الفلبين', 'Philippines'),
  Country('KH', 'كمبوديا', 'Cambodia'),
  Country('MM', 'ميانمار', 'Myanmar'),
  Country('LA', 'لاوس', 'Laos'),
  Country('CN', 'الصين', 'China'),
  Country('JP', 'اليابان', 'Japan'),
  Country('KR', 'كوريا الجنوبية', 'South Korea'),
  Country('KP', 'كوريا الشمالية', 'North Korea'),
  Country('MN', 'منغوليا', 'Mongolia'),
  Country('KZ', 'كازاخستان', 'Kazakhstan'),
  Country('UZ', 'أوزبكستان', 'Uzbekistan'),
  Country('TM', 'تركمانستان', 'Turkmenistan'),
  Country('TJ', 'طاجيكستان', 'Tajikistan'),
  Country('KG', 'قيرغيزستان', 'Kyrgyzstan'),
  Country('AZ', 'أذربيجان', 'Azerbaijan'),
  Country('AM', 'أرمينيا', 'Armenia'),
  Country('GE', 'جورجيا', 'Georgia'),
  Country('IL', 'إسرائيل', 'Israel'),
  Country('CY', 'قبرص', 'Cyprus'),
  Country('MV', 'المالديف', 'Maldives'),
  Country('BT', 'بوتان', 'Bhutan'),
  Country('TL', 'تيمور الشرقية', 'Timor-Leste'),
  // أوروبا
  Country('GB', 'بريطانيا', 'United Kingdom'),
  Country('IE', 'أيرلندا', 'Ireland'),
  Country('FR', 'فرنسا', 'France'),
  Country('DE', 'ألمانيا', 'Germany'),
  Country('IT', 'إيطاليا', 'Italy'),
  Country('ES', 'إسبانيا', 'Spain'),
  Country('PT', 'البرتغال', 'Portugal'),
  Country('NL', 'هولندا', 'Netherlands'),
  Country('BE', 'بلجيكا', 'Belgium'),
  Country('LU', 'لوكسمبورغ', 'Luxembourg'),
  Country('CH', 'سويسرا', 'Switzerland'),
  Country('AT', 'النمسا', 'Austria'),
  Country('SE', 'السويد', 'Sweden'),
  Country('NO', 'النرويج', 'Norway'),
  Country('DK', 'الدنمارك', 'Denmark'),
  Country('FI', 'فنلندا', 'Finland'),
  Country('IS', 'آيسلندا', 'Iceland'),
  Country('PL', 'بولندا', 'Poland'),
  Country('CZ', 'التشيك', 'Czechia'),
  Country('SK', 'سلوفاكيا', 'Slovakia'),
  Country('HU', 'المجر', 'Hungary'),
  Country('RO', 'رومانيا', 'Romania'),
  Country('BG', 'بلغاريا', 'Bulgaria'),
  Country('GR', 'اليونان', 'Greece'),
  Country('HR', 'كرواتيا', 'Croatia'),
  Country('SI', 'سلوفينيا', 'Slovenia'),
  Country('RS', 'صربيا', 'Serbia'),
  Country('BA', 'البوسنة والهرسك', 'Bosnia and Herzegovina'),
  Country('ME', 'الجبل الأسود', 'Montenegro'),
  Country('MK', 'مقدونيا الشمالية', 'North Macedonia'),
  Country('AL', 'ألبانيا', 'Albania'),
  Country('XK', 'كوسوفو', 'Kosovo'),
  Country('UA', 'أوكرانيا', 'Ukraine'),
  Country('BY', 'بيلاروسيا', 'Belarus'),
  Country('RU', 'روسيا', 'Russia'),
  Country('MD', 'مولدوفا', 'Moldova'),
  Country('LT', 'ليتوانيا', 'Lithuania'),
  Country('LV', 'لاتفيا', 'Latvia'),
  Country('EE', 'إستونيا', 'Estonia'),
  Country('MT', 'مالطا', 'Malta'),
  // أفريقيا
  Country('NG', 'نيجيريا', 'Nigeria'),
  Country('GH', 'غانا', 'Ghana'),
  Country('SN', 'السنغال', 'Senegal'),
  Country('CI', 'ساحل العاج', "Côte d'Ivoire"),
  Country('ML', 'مالي', 'Mali'),
  Country('NE', 'النيجر', 'Niger'),
  Country('BF', 'بوركينا فاسو', 'Burkina Faso'),
  Country('GN', 'غينيا', 'Guinea'),
  Country('TD', 'تشاد', 'Chad'),
  Country('CM', 'الكاميرون', 'Cameroon'),
  Country('ET', 'إثيوبيا', 'Ethiopia'),
  Country('ER', 'إريتريا', 'Eritrea'),
  Country('KE', 'كينيا', 'Kenya'),
  Country('TZ', 'تنزانيا', 'Tanzania'),
  Country('UG', 'أوغندا', 'Uganda'),
  Country('RW', 'رواندا', 'Rwanda'),
  Country('CD', 'الكونغو الديمقراطية', 'DR Congo'),
  Country('CG', 'الكونغو', 'Congo'),
  Country('AO', 'أنغولا', 'Angola'),
  Country('ZM', 'زامبيا', 'Zambia'),
  Country('ZW', 'زيمبابوي', 'Zimbabwe'),
  Country('MZ', 'موزمبيق', 'Mozambique'),
  Country('MW', 'مالاوي', 'Malawi'),
  Country('MG', 'مدغشقر', 'Madagascar'),
  Country('ZA', 'جنوب أفريقيا', 'South Africa'),
  Country('NA', 'ناميبيا', 'Namibia'),
  Country('BW', 'بوتسوانا', 'Botswana'),
  Country('SS', 'جنوب السودان', 'South Sudan'),
  Country('GA', 'الغابون', 'Gabon'),
  Country('GM', 'غامبيا', 'Gambia'),
  Country('SL', 'سيراليون', 'Sierra Leone'),
  Country('LR', 'ليبيريا', 'Liberia'),
  Country('TG', 'توغو', 'Togo'),
  Country('BJ', 'بنين', 'Benin'),
  Country('BI', 'بوروندي', 'Burundi'),
  // الأمريكتان
  Country('US', 'الولايات المتحدة', 'United States'),
  Country('CA', 'كندا', 'Canada'),
  Country('MX', 'المكسيك', 'Mexico'),
  Country('BR', 'البرازيل', 'Brazil'),
  Country('AR', 'الأرجنتين', 'Argentina'),
  Country('CL', 'تشيلي', 'Chile'),
  Country('CO', 'كولومبيا', 'Colombia'),
  Country('PE', 'بيرو', 'Peru'),
  Country('VE', 'فنزويلا', 'Venezuela'),
  Country('EC', 'الإكوادور', 'Ecuador'),
  Country('BO', 'بوليفيا', 'Bolivia'),
  Country('PY', 'باراغواي', 'Paraguay'),
  Country('UY', 'أوروغواي', 'Uruguay'),
  Country('CU', 'كوبا', 'Cuba'),
  Country('DO', 'الدومينيكان', 'Dominican Republic'),
  Country('GT', 'غواتيمالا', 'Guatemala'),
  Country('HN', 'هندوراس', 'Honduras'),
  Country('SV', 'السلفادور', 'El Salvador'),
  Country('NI', 'نيكاراغوا', 'Nicaragua'),
  Country('CR', 'كوستاريكا', 'Costa Rica'),
  Country('PA', 'بنما', 'Panama'),
  Country('JM', 'جامايكا', 'Jamaica'),
  Country('HT', 'هايتي', 'Haiti'),
  Country('TT', 'ترينيداد وتوباغو', 'Trinidad and Tobago'),
  // أوقيانوسيا
  Country('AU', 'أستراليا', 'Australia'),
  Country('NZ', 'نيوزيلندا', 'New Zealand'),
  Country('FJ', 'فيجي', 'Fiji'),
  Country('PG', 'بابوا غينيا الجديدة', 'Papua New Guinea'),
];

/// دولة بالكود.
Country? countryByCode(String? code) {
  if (code == null || code.isEmpty) return null;
  final up = code.toUpperCase();
  for (final c in kCountries) {
    if (c.code == up) return c;
  }
  return null;
}
